const catImages = [
  {
    id: 1,
    src: `${process.env.PUBLIC_URL}/img/img-1.jpg`,
    alt: "image-1",
    title: "image-1",
    height: 76,
    width: 66,
    description: "Selfies",
    selected: false,
    checked: false,
  },
  {
    id: 2,
    src: `${process.env.PUBLIC_URL}/img/img-1.jpeg`,
    alt: "image-2",
    title: "image-2",
    height: 76,
    width: 66,
    description: "Foods",
    selected: false,
    checked: false,
  },
  {
    id: 3,
    src: `${process.env.PUBLIC_URL}/img/img-3.jpg`,
    alt: "image-3",
    title: "image-3",
    height: 76,
    width: 66,
    description: "SnapShots",
    selected: false,
    checked: false,
  },
  {
    id: 4,
    src: `${process.env.PUBLIC_URL}/img/img-4.jpg`,
    alt: "image-4",
    title: "image-4",
    height: 76,
    width: 66,
    description: "People",
    selected: false,
    checked: false,
  },
];

const bodyImages = [
  {
    id: 5,
    src: `${process.env.PUBLIC_URL}/img/img-5.jpg`,
    alt: "image-5",
    title: "image-5",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 6,
    src: `${process.env.PUBLIC_URL}/img/img-6.jpg`,
    alt: "image-6",
    title: "image-6",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 7,
    src: `${process.env.PUBLIC_URL}/img/img-7.jpg`,
    alt: "image-7",
    title: "image-7",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 8,
    src: `${process.env.PUBLIC_URL}/img/img-8.jpg`,
    alt: "image-8",
    title: "image-8",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 9,
    src: `${process.env.PUBLIC_URL}/img/img-9.jpg`,
    alt: "image-9",
    title: "image-9",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 10,
    src: `${process.env.PUBLIC_URL}/img/img-10.jpg`,
    alt: "image-10",
    title: "image-10",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 11,
    src: `${process.env.PUBLIC_URL}/img/img-11.jpg`,
    alt: "image-11",
    title: "image-11",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 12,
    src: `${process.env.PUBLIC_URL}/img/img-12.jpg`,
    alt: "image-12",
    title: "image-12",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 13,
    src: `${process.env.PUBLIC_URL}/img/img-13.jpg`,
    alt: "image-13",
    title: "image-13",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 14,
    src: `${process.env.PUBLIC_URL}/img/img-14.jpg`,
    alt: "image-14",
    title: "image-14",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 15,
    src: `${process.env.PUBLIC_URL}/img/img-15.jpg`,
    alt: "image-15",
    title: "image-15",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 16,
    src: `${process.env.PUBLIC_URL}/img/img-1.jpg`,
    alt: "image-16",
    title: "image-16",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 17,
    src: `${process.env.PUBLIC_URL}/img/img-2.jpg`,
    alt: "image-17",
    title: "image-17",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 18,
    src: `${process.env.PUBLIC_URL}/img/img-3.jpg`,
    alt: "image-18",
    title: "image-18",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 19,
    src: `${process.env.PUBLIC_URL}/img/img-4.jpg`,
    alt: "image-19",
    title: "image-19",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 20,
    src: `${process.env.PUBLIC_URL}/img/img-5.jpg`,
    alt: "image-20",
    title: "image-20",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 21,
    src: `${process.env.PUBLIC_URL}/img/img-1.jpeg`,
    alt: "image-21",
    title: "image-21",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 22,
    src: `${process.env.PUBLIC_URL}/img/img-2.jpeg`,
    alt: "image-22",
    title: "image-22",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 23,
    src: `${process.env.PUBLIC_URL}/img/img-3.jpeg`,
    alt: "image-23",
    title: "image-23",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 24,
    src: `${process.env.PUBLIC_URL}/img/img-4.jpeg`,
    alt: "image-24",
    title: "image-24",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 25,
    src: `${process.env.PUBLIC_URL}/img/img-5.jpeg`,
    alt: "image-25",
    title: "image-25",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 26,
    src: `${process.env.PUBLIC_URL}/img/img-1.png`,
    alt: "image-26",
    title: "image-26",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 27,
    src: `${process.env.PUBLIC_URL}/img/img-2.png`,
    alt: "image-27",
    title: "image-27",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
  {
    id: 28,
    src: `${process.env.PUBLIC_URL}/img/img-1.webp`,
    alt: "image-28",
    title: "image-28",
    height: 90,
    width: 83,
    selected: false,
    checked: false,
  },
];

export { catImages, bodyImages };
